#!/usr/bin/env python3
"""Make every server item show properly in the renewal game, and build the Cash Shop from cashshop/shop.yml.

  python3 cashshop/build_shop.py          (then ./duds.sh package re, ./duds.sh up vm)

Every item in the renewal item DB is checked against the game client (client_data.py) and fixed:
  - no client entry         -> name + official English description (divine-pride.net) in client/itemInfo_RD.lua
  - no icon / floor sprite   -> real icon + collection picture (divine-pride); the floor sprite is copied from
                                a similar item. Cards use the client's generic card icon.
  - worn look not in client  -> server View set to one the client has (shop.yml "looks"), otherwise 0 (not
                                drawn): no more missing-sprite errors
Writes:
  deploy/re_db_import/item_cash.yml     the shop (from shop.yml)
  deploy/re_db_import/item_db.yml       the generated block at the end (View overrides)
  client/itemInfo_RD.lua                client item info for the items the client didn't know
  client/grf_items/…                    pictures, packed into ragnaduds.grf by package_client.py
                                        (git-ignored: Gravity's art)
Downloads are cached in cashshop/.cache/ (see item_assets.py): only the first run is slow.
"""
import os, re, shutil, sys, yaml

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
RATHENA = os.path.dirname(ROOT)
sys.path.insert(0, os.path.join(ROOT, "client"))
import grf  # noqa: E402
import item_assets  # noqa: E402
import script_desc  # noqa: E402
from client_data import Client, CLIENT, GRFS, UI, ITEM_SPR  # noqa: E402

SHOP = os.path.join(HERE, "shop.yml")
CASH_OUT = os.path.join(ROOT, "deploy", "re_db_import", "item_cash.yml")
ITEMDB = os.path.join(ROOT, "deploy", "re_db_import", "item_db.yml")
LUA_OUT = os.path.join(ROOT, "client", "itemInfo_RD.lua")
GRF_ITEMS = os.path.join(ROOT, "client", "grf_items")
MARK = "# ---- generated by cashshop/build_shop.py: looks the client can draw (do not edit below) ----"
HEAD = ("Head_Top", "Head_Mid", "Head_Low")
CARD_ICON = "이름없는카드"      # the client's generic card icon
HANGUL = re.compile("[\uac00-\ud7a3]")
CJK = re.compile("[\u3040-\u30ff\u4e00-\u9fff\uac00-\ud7a3]")      # Korean, Japanese, Chinese
DP_PLACEHOLDER = re.compile(r"Item #\d+ on Divine Pride")              # divine-pride page with no real text
APPLE = "사과"


def load_db():
    db = {}
    for f in ("item_db_equip.yml", "item_db_etc.yml", "item_db_usable.yml"):
        for it in yaml.safe_load(open(os.path.join(RATHENA, "db", "re", f)))["Body"] or []:
            db[it["Id"]] = it
    text = open(ITEMDB).read().split(MARK)[0]
    for it in (yaml.safe_load(text) or {}).get("Body") or []:
        db.setdefault(it["Id"], {}).update(it)
    return db


DESCRIBER = script_desc.Describer()


def english_desc(iid, item):
    """Official English description (divine-pride); if it's missing, a placeholder or not English (Korean/Japanese),
    one built from the server's item script (script_desc.py)."""
    desc = item_assets.description(iid)
    if desc and not any(CJK.search(d) for d in desc) and not any(DP_PLACEHOLDER.search(d) for d in desc):
        return [str(d) for d in desc]
    return [str(d) for d in DESCRIBER.describe(item)]


class Grfs:
    """Read files out of the client's archives (to copy floor sprites)."""
    def __init__(self):
        self.idx = {}
        for g in GRFS:
            f, entries = grf.entries(os.path.join(CLIENT, g))
            for n, e in entries.items():
                self.idx.setdefault(n.decode("cp949", "replace").lower(), (f, e))

    def get(self, name):
        hit = self.idx.get(name.lower())
        return grf.read(*hit) if hit else None


def lua_str(s):
    return '"' + str(s).replace("\\", "\\\\").replace('"', '\\"').replace("\n", " ") + '"'


# client weapon look of each weapon type (rAthena weapon_type order): the client draws a weapon from the item's
# ClassNum, and 0 means bare hands. Same numbers as the client's own generic weapons (Axe 1301: 6).
WEAPON_TYPES = {t: i for i, t in enumerate(["Fist", "Dagger", "1hSword", "2hSword", "1hSpear", "2hSpear", "1hAxe", "2hAxe",
                "Mace", "2hMace", "Staff", "Bow", "Knuckle", "Musical", "Whip", "Book", "Katar", "Revolver", "Rifle",
                "Gatling", "Shotgun", "Grenade", "Huuma", "2hStaff"])}


class Fixer:
    def __init__(self, db, client, looks_cfg):
        self.db, self.client, self.looks_cfg = db, client, looks_cfg
        self.grfs, self.donors = Grfs(), {}
        self.lua, self.views, self.files, self.log, self.texts = {}, {}, {}, [], {}
        self.slots = {}                     # shop.yml slots: item id -> card slots (our change to the official item)
        self.pictures = {}                  # shop.yml pictures: item id -> item whose icon / sprites / weapon look to use

    def kind(self, item):
        """Which look table draws this item on the character (normal and costume slots)."""
        locs = item.get("Locations") or {}
        if any(h in locs or f"Costume_{h}" in locs for h in HEAD): return "acc"
        if "Garment" in locs or "Costume_Garment" in locs: return "robe"
        if item.get("Type") == "Weapon": return "weapon"
        return None

    def weapon_look(self, item):
        """Most common look among weapons of the same type that the client can draw."""
        seen = {}
        for it in self.db.values():
            v = it.get("View")
            if it.get("Type") == "Weapon" and it.get("SubType") == item.get("SubType") and v \
                    and self.client.look_ok("weapon", v):
                seen[v] = seen.get(v, 0) + 1
        return max(seen, key=seen.get) if seen else 0

    def donor(self, item):
        """Resource name of an item of the same kind that the client shows fine (floor sprite to copy)."""
        loc = next(iter(item.get("Locations") or {"-": 1}))
        key = (item.get("Type"), loc, item.get("SubType"))
        if key not in self.donors:
            self.donors[key] = APPLE
            for it in self.db.values():
                if (it.get("Type"), next(iter(it.get("Locations") or {"-": 1})), it.get("SubType")) == key:
                    ci = self.client.info(it["Id"])
                    if ci and self.client.has_pictures(ci.get("identifiedResourceName")):
                        self.donors[key] = ci["identifiedResourceName"]; break
        return self.donors[key]

    def fix(self, item):
        iid, fixes = item["Id"], []
        ci = self.client.info(iid)
        is_card = item.get("Type") == "Card"
        resname = (ci or {}).get("identifiedResourceName") or (CARD_ICON if is_card else item["AegisName"])
        donor = self.client.info(self.pictures[iid]) if iid in self.pictures else None   # shop.yml pictures:
        if donor: resname = donor["identifiedResourceName"]
        # 1. worn look
        kind, view = self.kind(item), item.get("View")
        if kind and view and not self.client.look_ok(kind, view):
            new = self.looks_cfg.get(iid, 0)
            new = self.db[new].get("View", 0) if new in self.db else new
            if not new and kind == "weapon": new = self.weapon_look(item)
            self.views[iid] = (item["AegisName"], new); fixes.append(f"look {view}->{new or 'none'}")
            view = new
        # 2. client entry
        if not ci:
            desc = english_desc(iid, item)
            # the client's AddItem() needs strings for names and numbers for slots/look: never None
            self.lua[iid] = {"name": str(item.get("Name") or item["AegisName"]), "res": str(resname),
                             "desc": [str(d) for d in desc] or [str(item["AegisName"])],
                             "slots": int(item.get("Slots") or 0),
                             "view": int(donor.get("ClassNum") or 0) if donor else int(view or 0) if kind == "acc"
                                     else int(view or WEAPON_TYPES.get(item.get("SubType"), 0)) if kind == "weapon" else 0}
            fixes.append("client entry")
        # 2b. still Korean in the client (no English translation): English name (server) + description (divine-pride)
        elif ci:
            text = {}
            if HANGUL.search(str(ci.get("identifiedDisplayName", ""))):
                text["identifiedDisplayName"] = str(item.get("Name") or item["AegisName"])
                if HANGUL.search(str(ci.get("unidentifiedDisplayName", ""))): text["unidentifiedDisplayName"] = text["identifiedDisplayName"]
            if text or any(CJK.search(str(d)) for d in ci.get("identifiedDescriptionName") or []):
                text["identifiedDescriptionName"] = english_desc(iid, item)
            if text:
                self.texts[iid] = text; fixes.append("English text")
        # 3. pictures (cards: the generic card icon is always there)
        if not self.client.has_pictures(resname):
            icon, col = item_assets.icon_bmp(iid), item_assets.collection_bmp(iid)
            src = self.donor(item)
            if not icon:
                icon = self.grfs.get(f"data\\texture\\{UI}\\item\\{src}.bmp"); fixes.append(f"icon of {src}")
            if not col:
                col = self.grfs.get(f"data\\texture\\{UI}\\collection\\{src}.bmp")
            self.files[f"data\\texture\\{UI}\\item\\{resname}.bmp"] = icon
            if col: self.files[f"data\\texture\\{UI}\\collection\\{resname}.bmp"] = col
            for ext in ("spr", "act"):
                self.files[f"data\\sprite\\{ITEM_SPR}\\{resname}.{ext}"] = self.grfs.get(f"data\\sprite\\{ITEM_SPR}\\{src}.{ext}")
            fixes.append("pictures")
        if fixes:
            self.log.append(f"{iid:>7} {item.get('Name', '')[:38]:38} {', '.join(fixes)}")
        return fixes


CARD_TABLE = "data\\num2cardillustnametable.txt"   # card id -> picture name (data/texture/<UI>/cardbmp/<name>.bmp)


def fix_card_pictures(fixer, cards):
    """Shop cards whose big picture the client lacks ("resource file loading fail" on right-click): ship the
    divine-pride picture (or the closest card's, e.g. Sealed Drake -> Drake) in our GRF. A card with no line in
    the card table gets one APPENDED to the client's own table, byte for byte otherwise: rewriting existing lines
    (e.g. Meer's "300138#", which has no picture name) or adding a final line break crashes the 2026 client at
    start. Cards whose line exists with an empty name are left alone."""
    raw = fixer.grfs.get(CARD_TABLE)
    table = {int(p[0]): p[1] for p in (l.split("#") for l in raw.decode("cp949", "replace").splitlines())
             if len(p) >= 2 and p[0].strip().isdigit()}
    pre = f"data\\texture\\{UI}\\cardbmp\\".lower()
    have = {k[len(pre):-4] for k in fixer.grfs.idx if k.startswith(pre) and k.endswith(".bmp")}
    new_rows = {}
    for item in cards:
        iid = item["Id"]
        if iid in table and not table[iid]:
            continue                                   # empty name in the client's table: can't fix safely
        name = table.get(iid) or f"duds_card_{iid}"
        if name.lower() in have:
            continue
        bmp = item_assets.card_bmp(iid)
        if not bmp:
            donor = max((h for h in have if name.lower().endswith(h) and len(h) >= 4 and h != name.lower()), key=len, default=None)
            bmp = fixer.grfs.get(f"{pre}{donor}.bmp") if donor else None
        if not bmp:
            continue
        fixer.files[f"data\\texture\\{UI}\\cardbmp\\{name}.bmp"] = bmp
        fixer.log.append(f"{iid:>7} {item.get('Name', '')[:38]:38} card picture")
        if iid not in table:
            new_rows[iid] = name
    if new_rows:
        fixer.files[CARD_TABLE] = raw.rstrip(b"\r\n") + b"".join(f"\r\n{i}#{n}#".encode("cp949") for i, n in sorted(new_rows.items()))


def write_outputs(fixer, tabs_out):
    out = ["# RagnaDuds cash shop (renewal). GENERATED by cashshop/build_shop.py from cashshop/shop.yml: edit that.",
           "# Points: deploy/cash_points.txt. Refine certificates: Refine Master (prontera 184,177).",
           "Header:", "  Type: ITEM_CASH_DB", "  Version: 1", "", "Body:"]
    for tab, note, entries in tabs_out:
        if not entries: continue                 # empty tab (Sale): not written, the client hides it
        out += [f"  # {note}", f"  - Tab: {tab}", "    Items:"]
        for item, price in entries:
            out += [f"      - Item: {item['AegisName']}    # {item.get('Name', '')} ({item['Id']})", f"        Price: {price}"]
    open(CASH_OUT, "w").write("\n".join(out) + "\n")

    head = open(ITEMDB).read().split(MARK)[0].rstrip("\n")
    block = [MARK]
    for iid in sorted(set(fixer.views) | set(fixer.slots)):
        aegis = fixer.db[iid]["AegisName"]
        block += [f"  - Id: {iid}", f"    AegisName: {aegis}"]
        if iid in fixer.views: block.append(f"    View: {fixer.views[iid][1]}")
        if iid in fixer.slots: block.append(f"    Slots: {fixer.slots[iid]}")
    open(ITEMDB, "w").write(head + "\n" + "\n".join(block) + "\n")

    lines = ["-- RagnaDuds: client info for items this client doesn't have. GENERATED by cashshop/build_shop.py",
             "-- (descriptions: divine-pride.net). Loaded by System/itemInfo_true.lub after the kRO/English lists.",
             "tbl_ragnaduds = {"]
    for iid, v in sorted(fixer.lua.items()):
        desc = ", ".join(lua_str(d) for d in v["desc"])
        lines += [f"\t[{iid}] = {{",
                  f"\t\tunidentifiedDisplayName = {lua_str(v['name'])}, unidentifiedResourceName = {lua_str(v['res'])},",
                  "\t\tunidentifiedDescriptionName = { \"\" },",
                  f"\t\tidentifiedDisplayName = {lua_str(v['name'])}, identifiedResourceName = {lua_str(v['res'])},",
                  f"\t\tidentifiedDescriptionName = {{ {desc} }},",
                  f"\t\tslotCount = {v['slots']}, ClassNum = {v['view']}, costume = false",
                  "\t},"]
    for iid, n in sorted(fixer.slots.items()):             # shop.yml slots: card slots we added (partial entry)
        if iid not in fixer.lua: lines.append(f"\t[{iid}] = {{ slotCount = {n} }},")
    for iid, text in sorted(fixer.texts.items()):          # partial: only the Korean fields, merged by the loader
        fields = []
        for k, v in text.items():
            fields.append(f"{k} = {{ {', '.join(lua_str(d) for d in v)} }}" if isinstance(v, list) else f"{k} = {lua_str(v)}")
        lines.append(f"\t[{iid}] = {{ {', '.join(fields)} }},")
    lines.append("}")
    open(LUA_OUT, "w", encoding="cp949", errors="replace").write("\n".join(lines) + "\n")

    if os.path.isdir(GRF_ITEMS): shutil.rmtree(GRF_ITEMS)
    for name, data in fixer.files.items():
        if not data: continue
        p = os.path.join(GRF_ITEMS, *name.split("\\"))
        os.makedirs(os.path.dirname(p), exist_ok=True)
        open(p, "wb").write(data)


def main():
    shop = yaml.safe_load(open(SHOP))
    db, client = load_db(), Client()
    by_aegis = {it["AegisName"]: it for it in db.values() if "AegisName" in it}
    fixer = Fixer(db, client, {int(k): int(v) for k, v in (shop.get("looks") or {}).items()})
    fixer.slots = {int(k): int(v) for k, v in (shop.get("slots") or {}).items()}
    fixer.pictures = {int(k): int(v) for k, v in (shop.get("pictures") or {}).items()}
    for iid, n in fixer.slots.items():
        db[iid]["Slots"] = n                 # so new client entries (fixer.lua) get the same count

    for item in db.values():                 # every item the server has, not only the shop's
        if "AegisName" in item:
            fixer.fix(item)

    tabs_out, problems = [], []
    for tab, spec in shop["tabs"].items():
        entries = []
        for key, price in (spec.get("items") or {}).items():
            item = db.get(key) if isinstance(key, int) else by_aegis.get(key)
            if not item:
                problems.append(f"{tab}: {key} is not in the server item DB"); continue
            if price == "auto":
                lv = item.get("EquipLevelMin", 1)
                price = 100 if lv < 100 else 200 if lv < 170 else 400 if lv < 190 else 600
                if item.get("Type") == "Weapon": price = price * 3 // 2
            entries.append((item, price))
        tabs_out.append((tab, spec.get("note", ""), entries))
    if problems:
        sys.exit("fix shop.yml first:\n  " + "\n  ".join(problems))

    fix_card_pictures(fixer, [item for _, _, e in tabs_out for item, _ in e if item.get("Type") == "Card"])
    write_outputs(fixer, tabs_out)
    n = sum(len(e) for _, _, e in tabs_out)
    shop_ids = {item["Id"] for _, _, e in tabs_out for item, _ in e}
    print(f"shop: {n} items in {len(tabs_out)} tabs")
    print(f"fixed {len(fixer.log)} of {len(db)} items: {len(fixer.lua)} client entries, {len(fixer.texts)} translated, {len(fixer.views)} looks, "
          f"{sum(1 for d in fixer.files.values() if d)} picture files")
    for line in fixer.log:
        if int(line.split()[0]) in shop_ids: print("  shop " + line)


if __name__ == "__main__":
    main()
